### ISSUE TITLE
Java-SDK Central Maven Repository

### ISSUE THREAD

**Issue by ionsingo** [ALE-OPENNESS/Java-SDK#1]
Hey team,
I could not find the artifact in the central maven repository. Could you please check and reupload it?
Unfortunately I can't download github code within my company.
Kind regards

**Comment by MartinZabinskiDRV** [comment]
Hello,
we have the same problem. I mean we could compile it ourself and upload it in our internal repository, but your README says
"o2g java SDK is available on maven central repository."
so plz upload it. 
Thank you.

**Comment by fredmab** [comment]
There has been a publication error. Version 1.1.5 is available on maven at https://repo.maven.apache.org/maven2/io/github/ale-openness/o2g/o2g-sdk/

**Comment by MartinZabinskiDRV** [comment]
thank you
