### ISSUE TITLE
Not propagated exception in EventRegistar

### ISSUE THREAD

**Issue by fabianloewe** [ALE-OPENNESS/Java-SDK#2]
We receive events through the REST API. When using this SDK after registering a TelephonyEventListener and subscribing, no events are received and nothing happens. I followed the execution path during the subscription setup and found this part in the EventBuilder.java at lines 63-66:
```java
// ...
eventRegistrar.registerEventListener(ManagementEventListener.class);
eventRegistrar.registerAdapter("OnPbxObjectCreatedEvent", OnInternalPbxObjectEvent::adaptCreated, OnInternalPbxObjectEvent.class);
eventRegistrar.registerAdapter("OnPbxObjectDeletedEvent", OnInternalPbxObjectEvent::adaptDeleted, OnInternalPbxObjectEvent.class);
eventRegistrar.registerAdapter("OnPbxObjectModifiedEvent", OnInternalPbxObjectEvent::adaptModified, OnInternalPbxObjectEvent.class);   
// ...     
```

When `registerAdapter("OnPbxObjectCreatedEvent", ...)`is called, we end up here:
```java
public void registerAdapter(String eventName, EventAdapter adapter, Class<? extends O2GEvent> deserializeType) {
		
String qualifiedName = getQualifiedName(eventName);
if (qualifiedName == null) {
	// Warning !!
	/* ----> */ throw new Error(String.format("The specified event %s is not registered as an event", eventName));
}

adapters.put(qualifiedName, new EventTranslator(deserializeType, adapter));
}
```
This exception is thrown but never handled and logged or anything. My guess is, the execution silently fails at this point because this code is called inside a static block.

**Comment by fredmab** [comment]
Thank for the analysis, There were indeed a reflexion exception. name of the event is OnPbxObjectInstanceCreatedEvent.
Fixed in version 1.1.5 available on maven
