### ISSUE TITLE
How to terminate safely?

### ISSUE THREAD

**Issue by fabianloewe** [ALE-OPENNESS/Java-SDK#3]
Hello,

we encountered the problem that calling Session.listenEvents() will not halt the main thread. If the next statement is a call to Session.close(), all backgrounds threads and queues will be closed immediately again. This led us to the following questions:

1. Should we as SDK users lock the main thread? Could there be an option for the SDK to do it?
2. What is the best way to shutdown an application when we caught an error? Should we just call Session.close() (and then maybe exit() if necessary)? Is there more to do?

**Comment by fredmab** [comment]
There is no mechanism to lock the main thread in the SDK, so the application must do it if necessary.
The Session.close will close the session and all the allocated ressources. But it don't exit from the application.
SDK 1.2.0 has been released. It fix a bug in the close method when an event subscription has failed
